### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by williamjamir**
Requirements.txt from sphinx-click repository on github shows that this package works with `sphinx >=1.5,<2.3`.

https://github.com/click-contrib/sphinx-click/blob/master/requirements.txt

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by williamjamir** [comment]
@conda-forge-admin, please rerender

**Comment by williamjamir** [comment]
@CurtLH I've added an issue on https://github.com/click-contrib/sphinx-click/issues/54 questioning about the sphinx version.

So, perhaps this PR needs to be on hold until someone answer =)

**Comment by williamjamir** [comment]
@CurtLH 
I got an answer from the issue, and I think that the PR is ready to go =)
Is there anything else that you would like to add?

**Review by CurtLH — APPROVED** [review]
LGTM.  Thanks for helping to keep this aligned the the upstream package.

**Pull request merged**
